version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/unread_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=unread_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: